### ISSUE TITLE
Rejoining game after red card

### ISSUE THREAD

**Issue by Chalkeh** [romdi/IOS#176]
It would be handy if there was a "rejoin" button that appeared say 10 seconds before your player was allowed back on. If pressed during those 10 seconds, it'd queue you for auto-rejoining the game once the punishment is over.

**Comment by romdi** [comment]
The idea now is to have boxes at the top right of the screen showing the blocked position and re-join time in red. Maybe flash it when people can re-join the position. That way it's visible for everyone and no one can miss a red card.

**Comment by Aryan-5711** [comment]
Current way seems fine. Players should be aware till how long they are banned.

**Comment by romdi** [comment]
Should still show it in some way or at least notify everyone once the position is free again.

**Comment by Aryan-5711** [comment]
Thought about to NOT bench/spectate the red card player.
Kinda player responsibility to come back whenever timer runs out.

![298a864fb2d66840078015ae3fa0a3c7](https://cloud.githubusercontent.com/assets/2607436/10412624/ffaa9a88-6f8b-11e5-8f96-dae492eee884.png)

**Comment by romdi** [comment]
The current plan is the show a small red card near the scorebar, similar to how FIFA shows them. Maybe with the position name inside the card. When the card is expiring it should flash a couple of times, so everyone on the field and the spectators are aware that the position can be taken again.
