### ISSUE TITLE
SourceTV gets a yellow card/inherits players stats

### ISSUE THREAD

**Issue by Thinge** [romdi/IOS#194]
Sometimes SourceTV seems to get someones stats, which includes a yellow card that turns SourceTV's name yellow. It's stats mirror someone elses stats. This may happen often but you only notice when the player gets a yellow because SourceTV's name stands out. Poss % etc all matches to the players live stats. Seen it a few times lately.

**Comment by Aryan-5711** [comment]
Similar to #202 
Will close this since I haven't seen this bug for a long time even after I closed #202.
