### ISSUE TITLE
Red card/penalty foul replays

### ISSUE THREAD

**Issue by Thinge** [romdi/IOS#210]
I'd quite like to see replays implemented for fouls which lead to a penalty and also any red card fouls.

**Comment by Aryan-5711** [comment]
Do not think that this is a good idea. Replays shouldn't take too long and constant for every event. I already reduced each replays from 6 to 5 seconds, goal celebration from 8 to 5 seconds. Which makes total duration for celebration and replays for every goal 20 to 15 seconds. It simply takes too long and is more annoying than 'useful'. Definitely for the 'conceding' team that wish not to watch the replays that long.

It's not like real life that there could be a bad call when red card or foul is given.
