### ISSUE TITLE
Player attribute system

### ISSUE THREAD

**Issue by Aryan-5711** [romdi/IOS#235]
What attributes we can use in IOS for a player?

-Speed/Weight
-Stamina
-Size
-Strength
-more

I am definitely not a proponent of this but we have to take things into consideration.

**Comment by Aryan-5711** [comment]
Well like I said that I am not a fan of this idea. I know it's 1.1 but I hope it's not something that would be considered to be created as default IOS. That would be very bad.

**Comment by Orius** [comment]
I'll just drop the same piece that I said about Supraball wanting to do something similar;

The charm in a game like this is that everyone's equal. Everyone is equal and only the skill of the person makes the difference.
You can see the guy is better, but nothing withholds you from becoming that same guy if you try hard enough.

With different presets you take that away. So yes, in some ways it presents a deeper gameplay. With teams being able to apply complex tactics in regards to the classes. However it does take away that "Everyone is equal, it's all on your skill" idea. Sometimes less is more.

**Comment by romdi** [comment]
I know it's a controversial feature. It can add depth to the game and make it more interesting. But as you said, it removes equality of players on the field. I don't know yet if it will make it into the game and if yes when.

**Comment by Aryan-5711** [comment]
It's not just controversial. Its also a a total disaster if this gets implemented.
