### ISSUE TITLE
Seperate the gag option between voice and chat

### ISSUE THREAD

**Issue by Aryan-5711** [romdi/IOS#237]
For example I don't want to hear Xedem on the microphone but I wouldn't mind him chatting. But with the current gag system it gags them both which I don't like it either.

Something like:
Xedem id=6
For gagging voice: gag 6 voice
For gagging chat: gag 6 text/chat

**Comment by romdi** [comment]
Almost all multiplayer games seem to have a unified mute command which affects both text and voice. This also makes showing the mute status easier as you only need one icon which is on or off. So I decided not to change the way it works in Source by default.
