### ISSUE TITLE
Foul system

### ISSUE THREAD

**Issue by Aryan-5711** [romdi/IOS#301]
Problem at the moment is that a foul from side is never penalized with a yellow card.

**Comment by romdi** [comment]
Has been discussed. No change necessary.

**Comment by Aryan-5711** [comment]
Reopening due a new solution from the same idea.

Currently the yellow card decision depending on the distance of the foul.
I think that is fine for the first foul. The 2nd foul should always been rewarded with a yellow. 3rd depending again on distance and 4th is a guarantee yellow (2nd yellow mostly) again.

Foul 1 - Depending on distance
Foul 2 - Yellow card
Foul 3 - Depending on distance
Foul 4 - Yellow card (2nd yellow)

In case the player gets direct red or 2 yellows after 2nd or 3rd foul the system resets for that particular player.

**Comment by Aryan-5711** [comment]
Meh thinking about it. It ain't good if someone gets yellow for his 1st foul and following to this system gets 2nd yellow for his 2nd foul.
