### ISSUE TITLE
Tricks

### ISSUE THREAD

**Issue by Aryan-5711** [romdi/IOS#311]
We had an amount of tricks. Some could come back but some definitely don't.

Tricks that should come back:

1. Side dribbling
2. Lift ball up
3. Fake shot
4. Backheel

Those that don't

1. Back dribbling (unless it's on walk speed)
2. Rainbow flick (was bugged when we had it)
3. Roulette (totally useless)

**Comment by romdi** [comment]
It's probably best to bring back the free cam button for that and let players do tricks while holding that plus pressing other buttons:

While holding free cam button:

- M1 + Ball in front of player = Lift ball up
- M1 + Ball behind player = Rainbow flick
- A/D + M1 = Side dribbling (Player speed limited to run speed or lower)
- S + M1 = Back dribbling (Player speed limited to run speed or lower)
- W + M1 = Fake shot (Alternative: M2)
- Turn cam ~180° + M1 = Backheel
- Turn cam ~180° + M2 = Bicycle shot
