### ISSUE TITLE
Set-piece suggestions

### ISSUE THREAD

**Issue by Aryan-5711** [romdi/IOS#352]
- Make the player taker not able to move anywhere behind or sideways from the ball. This will avoid anything from an unexpected shot. 
- Outside that also if a player moves back from the ball he should be freezed for a couple of seconds so he is not able to trick the keeper. After 3 times it should be free-kick for the other team.
- Make free-kick delay depend on distance from opponent goal.

**Comment by romdi** [comment]
I don't think we should prevent players from moving.

This is what should suffice:

Use a line which is perpendicular to the line between the goal center and the set-piece position and move it back a couple of units away from the goal.
For penalties this is a line which is parallel to the goal line and lies between the penalty spot and the end of the penalty box.
Behind the line the player can move around freely.
Once he crosses the line he has to keep moving towards the goal center.
He can walk diagonally, but he can't move in an angle more than 90° away from the goal center.
Should he walk into an illegal direction or stop walking, all shots are instantly blocked.
He has to walk back behind the line to be able to shoot again.
