### ISSUE TITLE
Make chat lines disappear quicker

### ISSUE THREAD

**Issue by Aryan-5711** [romdi/IOS#372]
I believe that if I write something in-game that it remains too long. This could be reduced by 5 seconds or so.

**Comment by ziming** [comment]
Hmm, are you the Aryan I know?

**Comment by Aryan-5711** [comment]
Is this Polarbear?

**Comment by ziming** [comment]
Yea, it's been years since I last played IOS I think. Times are so different now.

**Comment by Aryan-5711** [comment]
Times changing! IOS is pretty much different than it used to be (b4, 2008 source etc). I think in a good way! Unfortunately we haven't reached a moment where we could make the game popular as it used to be. Some long delays made us still not reaching to the point where we could publish it. Despite that we are still busy and definitely not giving up. Game has simply too much potential.

New steam group: http://steamcommunity.com/groups/IOSoccer

**Comment by ziming** [comment]
Ah a pity Robert Kehres is mysteriously gone.

Yea, I think this game for some strange reasons always made me unable to leave it completely.
