### ISSUE TITLE
HUD

### ISSUE THREAD

**Issue by Aryan-5711** [romdi/IOS#384]
![9524943199919931610_screenshots_2015-07-24_00001](https://cloud.githubusercontent.com/assets/2607436/8868906/2b5b9b00-31de-11e5-96b0-1216df7f4017.jpg)

This could improve the HUD placement a lot.

Score bar - Left-top (good as it is)
Stamina bar - Right-top
Charge bar - Middle-down (only visible once activated)
Radar - Right-down (more down than image shows)
Chat - Left-down (more down than image shows)

Need a better event announcement.
Maybe also some player info (name, number and position) above stamina bar? Like in Football Superstars. https://www.youtube.com/watch?v=OkTlt5FmBEE

**Comment by ziming** [comment]
Wow this look really cool!

**Comment by romdi** [comment]
Done.
