### ISSUE TITLE
Make standing tackle foulable

### ISSUE THREAD

**Issue by Aryan14** [romdi/IOS#513]
Just like slide tackles it should go with a risk. However once this is implemented we can make standing tackle more stronger than it currently is.

**Comment by romdi** [comment]
I'm not sure we should do that as standing tackle was meant as a defender buff that allows a low-risk but limited attempt to kick the ball away. Making it foulable and buffing it might make it too similar to slide tackle.

**Comment by Aryan14** [comment]
This won't happen. Will find another way to balance things out. Closing this issue.
