### ISSUE TITLE
Red card isn't always the last man

### ISSUE THREAD

**Issue by Aryan14** [romdi/IOS#522]
Spoke about this a while ago. We agreed that there might be something incorrect with the distance to center of goal.

There are some red cards where it's highly questionable if the fouling player was indeed the last man to the goal.

**Comment by romdi** [comment]
Check should be like this (the fouling player will only be considered the last man if no other defender is inside the orange area):

![image](https://user-images.githubusercontent.com/198591/28247971-aa3fa0be-6a3b-11e7-8405-7ae351501830.png)

**Comment by Aryan14** [comment]
Video of a questionable red card: https://www.twitch.tv/videos/204803530?t=25m39s
