### ISSUE TITLE
Bunch of suggestions and ideas

### ISSUE THREAD

**Issue by EmperorAztec** [romdi/IOS#537]
First i just wanna say this is a great game with a lot of potential, and i love it.
Here are the suggestions:
- Add a votekick option for players who score own goals, bad GKs who don't wanna swap..etc
- Add a "gauge" to see how high the ball will go when you shoot (Kinda like a grenade launcher crosshair in COD)
- Make the players visible and sitting on the bench for immersion and make spectators visible on the stands
- Placeable cones in tutorial map, with some preset cones for a dribbling tutorial etc, also maybe placeable player dummies
-Maybe add an experience level (Doesn't have to affect anything) to know how good a player is, with some achievements likes score a bicycle kick..etc. to add a progression feel to the game and make new players feel like they're slowly improving.
-Increase the number count from 0-100 to 0-1000 for lolz
-Make fake clubs with fake kits and fake names, for diversity
-Make a referee show up and give the player a yellow/red card, while the players position themselves
-Improve the camera positioning so you can see both the player and the ball, like from a shoulder like angle

**Comment by Aryan14** [comment]
- We probably going to make some servers bots GK only and with human keeper we might have a voting system that will kick them. Although that isn't certain yet. Griefers will obviously be banned by our mods.

- Not sure about a height meter. It's in consideration though.

- In the current engine it's not a good idea to add more models that aren't human (not controlled). Would eat too much fps.

- Tutorial definitely will be improved and is one of our higher priority.
- Achievements will come as well
- We do not want to go higher than 2 digits on shirt number
- There will be more and improved generic kits and content on official servers
- Same thing with the bench models. It would not be good for optimization that is already limited in the current engine.
- So you want the camera to be offset from center? Not sure if that's good.
